// Generated by scripts/export_contracts.py from FastAPI OpenAPI.

export type ActivityObjective = {
  "activity_id": string;
  "contract_number": string;
  "completion_date": string | null;
  "overrun_days": number | null;
  "weight": string;
  "weighted_overrun": string | null;
};

export type AnalysisCreate = {
  "window_id": string;
  "scenario_id"?: string | null;
};

export type ApprovalDecision = {
  "stage_id": string;
  "decision": "approved" | "rejected";
  "comment": string;
};

export type ApprovalHistory = {
  "available": boolean;
  "reason": string;
  "history": Page_Entity_;
};

export type ApprovalSubmit = {
  "workflow_id": string;
  "expected_version": number;
};

export type AssignmentEdit = {
  "expected_version": number;
  "starts_at": string;
  "ends_at": string;
  "reason": string;
  "team_ids"?: (string)[] | null;
  "engineer_ids"?: (string)[] | null;
  "asset_ids"?: (string)[] | null;
  "sector_ids"?: (string)[] | null;
};

export type AssignmentOut = {
  "id": string;
  "scenario_id": string;
  "request_id": string;
  "starts_at": string;
  "ends_at": string;
  "original_start": string;
  "original_end": string;
  "feasible": boolean;
  "reason": string;
  [key:string]: unknown;
};

export type Availability = {
  "resource_id": string;
  "resource_type": "engineer" | "team" | "equipment";
  "availability": "available" | "unavailable" | "unknown";
  "qualified"?: boolean | null;
  "candidate_only"?: boolean;
  "complete_allocation_validation_performed"?: boolean;
};

export type CancelRequest = {
  "expected_version": number;
  "reason": string;
};

export type Capabilities = {
  "conflict_analysis_available"?: boolean;
  "optimisation_available"?: boolean;
  "copilot_available"?: boolean;
  "operational_approval_available"?: boolean;
};

export type CapacityGroup = {
  "co_share_group": string;
  "source": string;
  "activity_ids": (string)[];
};

export type CapacityHotspot = {
  "location_id": string;
  "week": number;
  "supply": number;
  "used": number;
  "excess": number;
  "possession_groups": (CapacityGroup)[];
};

export type Change = {
  "scenario_id": string;
  "request_id": string;
  "request_code": string;
  "original_start": string;
  "original_end": string;
  "starts_at": string;
  "ends_at": string;
  "reason": string;
  "replay_order": number;
};

export type CommandCentre = {
  "window": WindowOut;
  "requests": (RequestOut)[];
  "timeline": ({

})[];
  "conflicts": ({

})[] | null;
  "analysis": {

} | null;
  "scenarios": (ScenarioOut)[];
  "selected_scenario_id": string | null;
  "selected_scenario_version": number | null;
  "capabilities": Capabilities;
  "truncated": boolean;
};

export type Comparison = {
  "scenarios": (ScenarioOut)[];
  "conflict_resolution_comparable": boolean;
  "reason": string;
};

export type Completeness = {
  "activity_count": number;
  "activities_present": number;
  "activities_complete": number;
  "workload_gate_passed": boolean;
  "activities": (WorkloadItem)[];
};

export type Component = {
  "name": string;
  "score": number | null;
  "weight": number;
  "weighted_contribution": number | null;
  "status": "complete" | "partial" | "unknown" | "not_applicable";
  "evidence": (string)[];
  "missing_inputs": (string)[];
};

export type ConflictOut = {
  "id": string;
  "conflict_code": string;
  "analysis_run_id": string;
  "rule_id": string;
  "rule_code": string;
  "title": string;
  "explanation": string;
  "severity": string;
  "blocking": boolean;
  "lens": string;
  "risk_score": number | null;
  "detection_method": string;
  "resolution_status": string;
  "freshness": "unknown" | "stale" | "fresh";
  [key:string]: unknown;
};

export type ContractResult = {
  "contract_number": string;
  "simulated_completion_date": string | null;
  "overrun_days": number | null;
};

export type Entity = {
  "id": string;
  [key:string]: unknown;
};

export type EquipmentRequirement = {
  "type_id": string;
  "quantity"?: number;
};

export type ErrorBody = {
  "code": string;
  "message": string;
  "fields"?: ({

})[];
  "correlation_id": string;
  "guidance"?: string | null;
};

export type ErrorResponse = {
  "error": ErrorBody;
};

export type ExpectedVersion = {
  "expected_version": number;
};

export type GeoFeature = {
  "id": string;
  "type": "Feature";
  "geometry": {

} | null;
  "properties": {

};
  "geometry_available": boolean;
  "geometry_source": string;
  "name": string;
  [key:string]: unknown;
};

export type InstanceInput = {
  "name"?: string;
  "files": {
  [key:string]: string;
};
};

export type IsolationRequirement = {
  "isolation_zone_id": string;
  "required_state": "isolated" | "restored";
};

export type LockCreate = {
  "expected_version": number;
  "scenario_id"?: string | null;
  "reason": string;
  "fields"?: ("timing" | "team" | "engineers" | "equipment" | "sectors")[];
  "expires_at"?: string | null;
};

export type Mutation = {
  "id": string;
  "status": string;
  "version"?: number | null;
  "validation_status"?: string | null;
};

export type Named = {
  "id": string;
  "name": string;
  [key:string]: unknown;
};

export type ObjectiveComponents = {
  "overrun_days_total": number;
  "contracts_overrunning": number;
  "earliness_days_total": number;
  "priority_overrun": {
  [key:string]: number;
};
  "priority_weighted_overrun": string;
  "excess_access_nights_total": number;
  "excess_penalty": string;
  "eclo_nights_total": number;
  "eclo_penalty": string;
  "diagnostic_objective": string;
  "activity_components": (ActivityObjective)[];
  "contract_results": (ContractResult)[];
  "metrics_complete": boolean;
  "nights_scheduled": number;
  "formula": string;
};

export type OptimisationArtifacts = {
  "run_id": string;
  "files": {
  [key:string]: string;
};
  "physical_validation_complete": boolean;
  "judge_validation"?: string;
  "score_verification"?: string;
};

export type OptimisationCreate = {
  "window_id": string;
  "objective_id": string;
  "parameters"?: {

};
};

export type OptimisationDetail = {
  "run": {

};
  "result": OptimiseResult;
  "validation": {

} | null;
  "diagnostics": ({

})[];
  "contract_results": ({

})[];
};

export type OptimisationPage = {
  "items": ({

})[];
  "total": number;
  "limit": number;
  "offset": number;
};

export type OptimiseInput = {
  "time_limit_seconds"?: number;
  "deterministic_time_limit"?: number;
  "random_seed"?: number;
  "physical_nights_per_week"?: number;
  "locked_placements"?: (Placement)[];
  "baseline_placements"?: (Placement)[];
};

export type OptimiseResult = {
  "scenario"?: "A" | "B" | "C";
  "optimiser_version"?: string;
  "solver_status": string;
  "publishable"?: boolean;
  "primary_optimal"?: boolean;
  "lexicographic_complete"?: boolean;
  "solve_time_seconds": number;
  "objective_components"?: {

} | null;
  "submission_files"?: {
  [key:string]: string;
} | null;
  "physical_nights"?: (Placement)[];
  "physical_validation_complete"?: boolean;
  "validation_report"?: ValidationReport | null;
  "completion_changes"?: ({

})[];
  "workload_delivery"?: ({

})[];
  "capacity_hotspots"?: ({

})[];
  "baseline_movement"?: number;
  "contract_completion_gate"?: boolean;
  "eclo_windows"?: {
  [key:string]: {

};
};
  "cross_line_eclo_activities"?: (string)[];
  "diagnostics"?: ({

})[];
  "stages"?: ({

})[];
  "settings": {

};
  "failed_candidate"?: {

} | null;
  "judge_validation"?: "not_run";
  "score_verification"?: "internal_only";
};

export type Page_Availability_ = {
  "items": (Availability)[];
  "limit": number;
  "offset": number;
  "total": number;
};

export type Page_Change_ = {
  "items": (Change)[];
  "limit": number;
  "offset": number;
  "total": number;
};

export type Page_ConflictOut_ = {
  "items": (ConflictOut)[];
  "limit": number;
  "offset": number;
  "total": number;
};

export type Page_Entity_ = {
  "items": (Entity)[];
  "limit": number;
  "offset": number;
  "total": number;
};

export type Page_GeoFeature_ = {
  "items": (GeoFeature)[];
  "limit": number;
  "offset": number;
  "total": number;
};

export type Page_Named_ = {
  "items": (Named)[];
  "limit": number;
  "offset": number;
  "total": number;
};

export type Page_RequestOut_ = {
  "items": (RequestOut)[];
  "limit": number;
  "offset": number;
  "total": number;
};

export type Page_ScenarioOut_ = {
  "items": (ScenarioOut)[];
  "limit": number;
  "offset": number;
  "total": number;
};

export type Page_ScoreOut_ = {
  "items": (ScoreOut)[];
  "limit": number;
  "offset": number;
  "total": number;
};

export type Page_WindowOut_ = {
  "items": (WindowOut)[];
  "limit": number;
  "offset": number;
  "total": number;
};

export type Placement = {
  "activity_id": string;
  "access_seq": number;
  "week": number;
  "physical_night": number;
  "access_night"?: number | null;
  "eclo"?: number | null;
  "co_share_group"?: string | null;
};

export type PolicyCreate = {
  "code"?: string;
  "version"?: number;
  "weights"?: {
  [key:string]: number | string;
};
  "description"?: string;
};

export type Preview = {
  "basic_valid": boolean;
  "issues": (string)[];
  "starts_at": string;
  "ends_at": string;
  "complete_conflict_validation_performed"?: boolean;
  "analysis_required"?: boolean;
  "scenario_version": number;
};

export type PreviewInput = {
  "scenario": "A" | "B" | "C";
  "files": {
  [key:string]: string;
};
  "idempotency_key"?: string | null;
  "instance_files": {
  [key:string]: string;
};
};

export type ReadEvents = {
  "event_ids": (string)[];
};

export type ReadResult = {
  "marked_read": number;
};

export type ReferenceData = {
  "priorities": (string)[];
  "capabilities": Capabilities;
  "limit_per_collection": number;
  "resource_lists_url": string;
  "collections_may_be_truncated": boolean;
  "work_types": (Named)[];
  "request_statuses": (Entity)[];
  "equipment_types": (Named)[];
  "skills": (Named)[];
  "optimisation_objectives": (Named)[];
  "teams": (Named)[];
  "isolation_zones": (Named)[];
};

export type ReleaseLock = {
  "reason": string;
};

export type RequestCreate = {
  "submit"?: boolean;
  "window_id": string;
  "work_type_id": string;
  "title": string;
  "description"?: string;
  "requested_start": string;
  "requested_end": string;
  "earliest_start": string;
  "latest_finish": string;
  "min_duration_minutes": number;
  "max_duration_minutes": number;
  "priority"?: "normal" | "high" | "urgent";
  "sector_ids": (string)[];
  "team_ids"?: (string)[];
  "engineer_ids"?: (string)[];
  "workzone_ids"?: (string)[];
  "equipment"?: (EquipmentRequirement)[];
  "skills"?: (SkillRequirement)[];
  "isolations"?: (IsolationRequirement)[];
};

export type RequestOut = {
  "id": string;
  "request_code": string;
  "title": string;
  "description": string;
  "window_id": string;
  "requested_start": string;
  "requested_end": string;
  "version": number;
  "status_code": string;
  "priority": string;
  [key:string]: unknown;
};

export type RequestPatch = {
  "expected_version": number;
  "work_type_id"?: string | null;
  "sector_ids"?: (string)[] | null;
  "team_ids"?: (string)[] | null;
  "engineer_ids"?: (string)[] | null;
  "workzone_ids"?: (string)[] | null;
  "equipment"?: (EquipmentRequirement)[] | null;
  "skills"?: (SkillRequirement)[] | null;
  "isolations"?: (IsolationRequirement)[] | null;
  "title"?: string | null;
  "description"?: string | null;
  "priority"?: "normal" | "high" | "urgent" | null;
  "requested_start"?: string | null;
  "requested_end"?: string | null;
  "earliest_start"?: string | null;
  "latest_finish"?: string | null;
  "min_duration_minutes"?: number | null;
  "max_duration_minutes"?: number | null;
};

export type SavedOptimiseInput = {
  "time_limit_seconds"?: number;
  "deterministic_time_limit"?: number;
  "random_seed"?: number;
  "physical_nights_per_week"?: number;
  "locked_placements"?: (Placement)[];
  "baseline_placements"?: (Placement)[];
  "baseline_run_id"?: string | null;
  "idempotency_key"?: string | null;
};

export type SavedOptimiseResult = {
  "scenario"?: "A" | "B" | "C";
  "optimiser_version"?: string;
  "solver_status": string;
  "publishable"?: boolean;
  "primary_optimal"?: boolean;
  "lexicographic_complete"?: boolean;
  "solve_time_seconds": number;
  "objective_components"?: {

} | null;
  "submission_files"?: {
  [key:string]: string;
} | null;
  "physical_nights"?: (Placement)[];
  "physical_validation_complete"?: boolean;
  "validation_report"?: ValidationReport | null;
  "completion_changes"?: ({

})[];
  "workload_delivery"?: ({

})[];
  "capacity_hotspots"?: ({

})[];
  "baseline_movement"?: number;
  "contract_completion_gate"?: boolean;
  "eclo_windows"?: {
  [key:string]: {

};
};
  "cross_line_eclo_activities"?: (string)[];
  "diagnostics"?: ({

})[];
  "stages"?: ({

})[];
  "settings": {

};
  "failed_candidate"?: {

} | null;
  "judge_validation"?: "not_run";
  "score_verification"?: "internal_only";
  "run_id": string;
  "created": boolean;
  "reused": boolean;
  "created_at": string;
  "terminal_outcome": string;
  "input_fingerprint": string;
};

export type SavedValidation = {
  "id": string;
  "created": boolean;
  "report": ValidationReport;
};

export type ScenarioBPreviewInput = {
  "time_limit_seconds"?: number;
  "deterministic_time_limit"?: number;
  "random_seed"?: number;
  "physical_nights_per_week"?: number;
  "locked_placements"?: (Placement)[];
  "baseline_placements"?: (Placement)[];
  "instance_files": {
  [key:string]: string;
};
};

export type ScenarioCPreviewInput = {
  "time_limit_seconds"?: number;
  "deterministic_time_limit"?: number;
  "random_seed"?: number;
  "physical_nights_per_week"?: number;
  "locked_placements"?: (Placement)[];
  "baseline_placements"?: (Placement)[];
  "instance_files": {
  [key:string]: string;
};
};

export type ScenarioClone = {
  "expected_version": number;
  "name": string;
};

export type ScenarioCreate = {
  "window_id": string;
  "objective_id": string;
  "name": string;
};

export type ScenarioDetail = {
  "summary": ScenarioOut;
  "assignments": (AssignmentOut)[];
  "changes": ({

})[];
  "analysis": {

} | null;
  "capabilities": Capabilities;
};

export type ScenarioOut = {
  "id": string;
  "name": string;
  "status": string;
  "version": number;
  "validation_status": string;
  "provenance": string;
  [key:string]: unknown;
};

export type ScoreCreate = {
  "policy_id": string;
  "expected_conflict_version": number;
  "expected_input_fingerprint": string;
  "idempotency_key": string;
};

export type ScoreOut = {
  "id": string;
  "conflict_id": string;
  "policy_id": string;
  "input_fingerprint": string;
  "policy_fingerprint": string;
  "source_revision": number;
  "engine_version": string;
  "result": ScoreResult;
  "freshness": string;
  "active_policy_matches": boolean;
  "can_certify_current_schedule"?: boolean;
  [key:string]: unknown;
};

export type ScoreResult = {
  "engine_version": string;
  "rule_severity": string;
  "risk_score": number | null;
  "risk_upper_bound": number | null;
  "risk_band": string | null;
  "effective_severity": string;
  "blocking": boolean;
  "score_status": "complete" | "partial" | "unknown";
  "confidence": number;
  "coverage": number;
  "synthetic": boolean;
  "policy_validated": boolean;
  "eligible_for_auto_prioritisation": boolean;
  "explanation": string;
  "components": (Component)[];
};

export type SkillRequirement = {
  "skill_id": string;
  "required_count"?: number;
};

export type SubmissionInput = {
  "scenario": "A" | "B" | "C";
  "files": {
  [key:string]: string;
};
  "idempotency_key"?: string | null;
};

export type TimelineItem = {
  "request_id": string;
  "request_code": string;
  "title": string;
  "window_id": string;
  "scenario_id": string | null;
  "starts_at": string;
  "ends_at": string;
  "original_start": string;
  "original_end": string;
  "movement_minutes": number;
  "moved": boolean;
  "priority": string;
};

export type ValidationReport = {
  "validation_context"?: "submission" | "rich_schedule";
  "physical_validation_complete"?: boolean;
  "scenario": "A" | "B" | "C";
  "feasible": boolean;
  "validation_status": "invalid_submission" | "infeasible" | "feasible";
  "validator_version": string;
  "dataset_fingerprint": string;
  "submission_fingerprint": string;
  "rule_policy": {

};
  "hard_violations": (Violation)[];
  "warnings": ({

})[];
  "objective_components": ObjectiveComponents;
  "objective_score": string | null;
  "completeness": Completeness;
  "capacity_hotspots": (CapacityHotspot)[];
  "active_rule_assumptions": (string)[];
  "judge_validation"?: "not_run";
  "score_verification"?: "internal_only";
};

export type Violation = {
  "rule_code": string;
  "message": string;
  "week"?: number | null;
  "activity_ids"?: (string)[];
  "contract_ids"?: (string)[];
  "location_ids"?: (string)[];
  "possession_group"?: {

} | null;
  "evidence"?: {

};
};

export type WindowOut = {
  "id": string;
  "name": string;
  "starts_at": string;
  "ends_at": string;
  "timezone": string;
  "version": number;
  [key:string]: unknown;
};

export type WorkloadItem = {
  "activity_id": string;
  "contract_number": string;
  "required": string;
  "delivered": string;
  "standard_access_contribution": string;
  "eclo_contribution": string;
  "shortfall": string;
  "over_delivery": string;
  "present": boolean;
  "complete": boolean;
};
