-- Generated by scripts/export_engine_rules.py; SYNTHETIC policies only.
INSERT INTO railplan.rule_definitions
          (id,code,version,name,category,severity,blocking,enabled,authority_reference)
          VALUES ('bd0ff93d-bef5-50c6-9ba9-445d1440fa33','CE-TRACK',1,'Incompatible sector occupancy','Possession','critical',true,true,
          'SYNTHETIC - not an operational rule') ON CONFLICT (code,version) DO NOTHING;
INSERT INTO railplan.rule_definitions
          (id,code,version,name,category,severity,blocking,enabled,authority_reference)
          VALUES ('e11bbd8a-f971-5e68-856a-91289694b17c','CE-SPATIAL',1,'Workzone separation','Possession','critical',true,true,
          'SYNTHETIC - not an operational rule') ON CONFLICT (code,version) DO NOTHING;
INSERT INTO railplan.rule_definitions
          (id,code,version,name,category,severity,blocking,enabled,authority_reference)
          VALUES ('5c0ae46e-dd33-56bb-83ba-38c4df8cc0a4','CE-ISOLATION',1,'Contradictory isolation states','Isolation','critical',true,true,
          'SYNTHETIC - not an operational rule') ON CONFLICT (code,version) DO NOTHING;
INSERT INTO railplan.rule_definitions
          (id,code,version,name,category,severity,blocking,enabled,authority_reference)
          VALUES ('67e9f38a-afa3-59f8-a439-d79f1a2cc1e7','CE-ENGINEER',1,'Engineer double booking','Manpower','high',true,true,
          'SYNTHETIC - not an operational rule') ON CONFLICT (code,version) DO NOTHING;
INSERT INTO railplan.rule_definitions
          (id,code,version,name,category,severity,blocking,enabled,authority_reference)
          VALUES ('d7222297-ff7f-5e09-bcd3-4c8e1e93c76a','CE-TEAM',1,'Team double booking','Manpower','high',true,true,
          'SYNTHETIC - not an operational rule') ON CONFLICT (code,version) DO NOTHING;
INSERT INTO railplan.rule_definitions
          (id,code,version,name,category,severity,blocking,enabled,authority_reference)
          VALUES ('ab083f81-0ffe-5c29-aeb5-dd5923b054c0','CE-ASSET',1,'Equipment double booking','Equipment','high',true,true,
          'SYNTHETIC - not an operational rule') ON CONFLICT (code,version) DO NOTHING;
INSERT INTO railplan.rule_definitions
          (id,code,version,name,category,severity,blocking,enabled,authority_reference)
          VALUES ('d7f5d350-fca7-5cbe-9abd-20cc7dd41448','CE-AVAILABILITY',1,'Resource availability','Resources','high',true,true,
          'SYNTHETIC - not an operational rule') ON CONFLICT (code,version) DO NOTHING;
INSERT INTO railplan.rule_definitions
          (id,code,version,name,category,severity,blocking,enabled,authority_reference)
          VALUES ('1652abc2-1075-5fd2-8317-bbd562f1c51e','CE-SKILL',1,'Qualified headcount','Manpower','high',true,true,
          'SYNTHETIC - not an operational rule') ON CONFLICT (code,version) DO NOTHING;
INSERT INTO railplan.rule_definitions
          (id,code,version,name,category,severity,blocking,enabled,authority_reference)
          VALUES ('49255972-f3d9-5012-ae9b-219f69f3c9c3','CE-EQUIPMENT',1,'Equipment quantity or capability','Equipment','high',true,true,
          'SYNTHETIC - not an operational rule') ON CONFLICT (code,version) DO NOTHING;
INSERT INTO railplan.rule_definitions
          (id,code,version,name,category,severity,blocking,enabled,authority_reference)
          VALUES ('cfc4bee9-41c9-5581-a28c-e2305a88b22e','CE-WINDOW',1,'Engineering window or sector availability','Possession','high',true,true,
          'SYNTHETIC - not an operational rule') ON CONFLICT (code,version) DO NOTHING;
INSERT INTO railplan.rule_definitions
          (id,code,version,name,category,severity,blocking,enabled,authority_reference)
          VALUES ('d2428008-e4eb-5947-aae0-e82d75aa857a','CE-DEPENDENCY',1,'Dependency ordering','Dependencies','high',true,true,
          'SYNTHETIC - not an operational rule') ON CONFLICT (code,version) DO NOTHING;
INSERT INTO railplan.rule_definitions
          (id,code,version,name,category,severity,blocking,enabled,authority_reference)
          VALUES ('5ea14335-cadc-5b3a-af6c-83248d0d22f1','CE-TRAVEL',1,'Engineer travel time','Manpower','high',true,true,
          'SYNTHETIC - not an operational rule') ON CONFLICT (code,version) DO NOTHING;
INSERT INTO railplan.rule_definitions
          (id,code,version,name,category,severity,blocking,enabled,authority_reference)
          VALUES ('c02f66c7-5e6f-5e6c-aeaf-eda8934e8764','CE-REVIEW',1,'Incomplete data requires review','Review','information',true,true,
          'SYNTHETIC - not an operational rule') ON CONFLICT (code,version) DO NOTHING;
INSERT INTO railplan.compatibility_rules
      (id,first_work_type_id,second_work_type_id,compatible,version,rationale)
      SELECT 'f76c165c-329a-5cfe-9fdd-9bac09222811',least(a.id,b.id),greatest(a.id,b.id),false,1,
        'SYNTHETIC - signal inspection and rail renewal are exclusive in this demo'
      FROM railplan.work_types a CROSS JOIN railplan.work_types b
      WHERE a.id='9e68f1fd-909b-5e53-b1f0-fa060d8540eb' AND b.id='caade90a-407e-5979-85da-5f164b4408bc'
      ON CONFLICT(first_work_type_id,second_work_type_id,version) DO NOTHING;
