'use client';
import {useState,useEffect,useMemo,useRef,Suspense,Component,type ReactNode} from 'react';
import {Canvas,useFrame} from '@react-three/fiber';
import {OrbitControls,Html,Line} from '@react-three/drei';
import * as THREE from 'three';
import {Plus,Minus,RotateCcw,Navigation,Focus,Layers,ArrowLeft,ArrowRight,Search,Maximize2} from 'lucide-react';
import coast from './singapore-coast.json';
import {places,railLines,project,zones} from './singapore-data';
type Props={selected:string;location:string;onSelect:(id:string)=>void;resolved:boolean;busy:boolean;lens:string;locked:boolean;focus:boolean;presentation:boolean};
class MapBoundary extends Component<{children:ReactNode;fallback:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true}}render(){return this.state.failed?this.props.fallback:this.props.children}}
const position=(name:string):[number,number,number]=>{const p=project(places[name]||places.Bishan);return [p[0],.23,-p[1]]};
function Scene({station,selected,onSelect,resolved,busy,lens,mode,command,orbit,locked,lineFilter,reduced}:any){
 const controls=useRef<any>(null),goal=useRef<any>(null),ring=useRef<THREE.Mesh>(null);
 const shapes=useMemo(()=>coast.map((polygon:any)=>{const shape=new THREE.Shape();polygon[0].forEach((p:number[],i:number)=>{const [x,y]=project(p);i?shape.lineTo(x,y):shape.moveTo(x,y)});return shape}),[]);
 useEffect(()=>{if(!controls.current)return;const c=controls.current;const p=position(station);if(command.kind==='reset'){goal.current={target:new THREE.Vector3(0,0,0),pos:new THREE.Vector3(0,13,13)}}else if(command.kind==='focus'||command.kind==='track'){const target=new THREE.Vector3(p[0],0,p[2]);goal.current={target,pos:target.clone().add(new THREE.Vector3(0,command.kind==='track'?2.8:5,command.kind==='track'?2:4))}}else if(command.kind==='zoom'){const v=c.object.position.clone().sub(c.target).multiplyScalar(command.value);v.clampLength(2.5,27);goal.current={target:c.target.clone(),pos:c.target.clone().add(v)}}else if(command.kind==='rotate'){const v=c.object.position.clone().sub(c.target).applyAxisAngle(new THREE.Vector3(0,1,0),command.value);goal.current={target:c.target.clone(),pos:c.target.clone().add(v)}}else if(command.kind==='north'){goal.current={target:c.target.clone(),pos:c.target.clone().add(new THREE.Vector3(0,14,.01))}}},[command,station]);
 useFrame((state,delta)=>{if(goal.current&&controls.current){const c=controls.current;c.target.lerp(goal.current.target,Math.min(1,delta*(reduced?1000:5)));c.object.position.lerp(goal.current.pos,Math.min(1,delta*(reduced?1000:5)));c.update();if(c.object.position.distanceTo(goal.current.pos)<.015)goal.current=null}if(ring.current){const s=busy?1+Math.sin(state.clock.elapsedTime*3)*.2:1;ring.current.scale.setScalar(s)}});
 return <><ambientLight intensity={1.5}/><directionalLight position={[4,12,5]} intensity={2.4} color="#fff4e7"/><directionalLight position={[-6,5,-6]} intensity={1.5} color="#b8c3ff"/>
 <mesh position={[0,-.48,0]}><cylinderGeometry args={[9.7,9.6,.28,96]}/><meshStandardMaterial color="#e4e4f7" roughness={.3}/></mesh><mesh rotation={[-Math.PI/2,0,0]} position={[0,-.32,0]}><circleGeometry args={[9.55,96]}/><meshStandardMaterial color="#d8ecf1" roughness={.24}/></mesh>
 {shapes.map((shape,i)=><mesh key={i} rotation={[-Math.PI/2,0,0]} position={[0,-.18,0]}><extrudeGeometry args={[shape,{depth:.35,bevelEnabled:false}]}/><meshStandardMaterial color={mode==='schematic'?'#eff0ff':'#dce7d6'} roughness={.6}/></mesh>)}
 {railLines.filter(line=>lineFilter==='All'||line.code===lineFilter).map(line=><Line key={line.name} points={line.names.map(position)} color={line.color} lineWidth={selected&&lens!=='All systems'&&line.code!=='NSL'?1.5:3} transparent opacity={lens!=='All systems'&&line.code!=='NSL'?.25:1}/>)}
 {Object.keys(places).map(name=><mesh key={name} position={position(name)} onClick={e=>{e.stopPropagation();onSelect(name)}} onPointerOver={()=>document.body.style.cursor='pointer'} onPointerOut={()=>document.body.style.cursor='auto'}><sphereGeometry args={[name===station?.085:.045,12,8]}/><meshStandardMaterial color={name===station?'#8061ef':'#ffffff'} emissive="#ffffff" emissiveIntensity={.15}/>{(name===station||['Woodlands','Jurong East','Paya Lebar','Punggol','Changi Airport','HarbourFront','Marina Bay'].includes(name))&&<Html center position={[0,.12,0]} distanceFactor={14} zIndexRange={[20,0]}><button className="map-station" onClick={()=>onSelect(name)}>{name}</button></Html>}</mesh>)}
 {zones.map(z=>{const p=position(z.station),active=z.station===station;const color=resolved?'#18b88c':z.color;return <group key={z.name} position={p}><mesh rotation={[-Math.PI/2,0,0]} position={[0,.015,0]} ref={active?ring:undefined}><ringGeometry args={[active?.23:.15,active?.62:.38,48]}/><meshBasicMaterial color={color} transparent opacity={active?.35:.18} side={THREE.DoubleSide}/></mesh><mesh position={[0,.34,0]} onClick={()=>onSelect(z.station)}><cylinderGeometry args={[.025,.025,.65,12]}/><meshStandardMaterial color={color}/></mesh><mesh position={[0,.71,0]} onClick={()=>onSelect(z.station)}><sphereGeometry args={[active?.16:.12,20,16]}/><meshStandardMaterial color={color} roughness={.25}/></mesh><Html center position={[0,1,0]} zIndexRange={[25,0]}><button className={`map-pin ${active?'selected':''}`} style={{'--pin':color} as any} onClick={()=>onSelect(z.station)}><i/>{z.name}<small>{active&&locked?'Locked · ':''}{resolved?'Coordinated':z.state}</small></button></Html></group>})}
 {mode==='track'&&<group position={position(station)}><Line points={[[-.7,.06,-1],[-.7,.06,1]]} color="#666a89" lineWidth={5}/><Line points={[[.7,.06,-1],[.7,.06,1]]} color="#666a89" lineWidth={5}/><Html position={[0,.4,0]} center><div className="track-card"><b>{station}</b><span>Up track / Down track</span><span>Illustrative possession detail</span><strong>{selected}</strong></div></Html></group>}
 <OrbitControls ref={controls} makeDefault minDistance={2.5} maxDistance={27} maxPolarAngle={Math.PI/2.2} minPolarAngle={.02} enableDamping dampingFactor={.08} autoRotate={orbit&&!reduced} autoRotateSpeed={.3} onStart={()=>goal.current=null}/></>;
}
export default function SingaporeMap(props:Props){const [station,setStation]=useState('Bishan'),[mode,setMode]=useState('3d'),[cmd,setCmd]=useState({kind:'reset',value:0,nonce:0}),[orbit,setOrbit]=useState(false),[search,setSearch]=useState(''),[line,setLine]=useState('All'),[reduced,setReduced]=useState(false);
 useEffect(()=>{const m=window.matchMedia('(prefers-reduced-motion: reduce)');setReduced(m.matches);const f=()=>setReduced(m.matches);m.addEventListener('change',f);return()=>m.removeEventListener('change',f)},[]);
 useEffect(()=>{setOrbit(props.presentation)},[props.presentation]);const send=(kind:string,value=0)=>setCmd({kind,value,nonce:Date.now()});
 useEffect(()=>{const s=Object.keys(places).find(n=>props.location.startsWith(n))||'Bishan';setStation(s);if(props.focus)send('focus')},[props.selected,props.location,props.focus]);
 const choose=(s:string)=>{setStation(s);setSearch('');send('focus');const z=zones.find(z=>z.station===s);const next=z?.id||({'Braddell':'MR-031','Toa Payoh':'MR-040','Novena':'MR-042','Newton':'MR-056','Orchard':'MR-056'} as Record<string,string>)[s];if(next)props.onSelect(next)};
 const list=<div className="map-fallback"><h3>Singapore workzones</h3>{zones.map(z=><button onClick={()=>choose(z.station)} key={z.id}>{z.name} · {z.state}</button>)}</div>;
 return <section className={`spatial-map ${props.busy?'scanning':''}`}><div className="map-top"><div><span className="eyebrow">SINGAPORE / SPATIAL WORKSPACE</span><h2>{station}<span> · {mode==='track'?'Track detail':'Network overview'}</span></h2></div><div className="map-search"><Search size={15}/><input aria-label="Find a station" placeholder="Find a station…" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<div className="map-results">{Object.keys(places).filter(s=>s.toLowerCase().includes(search.toLowerCase())).slice(0,7).map(s=><button key={s} onClick={()=>choose(s)}>{s}</button>)}</div>}</div></div>
 <MapBoundary fallback={list}><Suspense fallback={<div className="map-loading">Preparing Singapore network…</div>}><Canvas camera={{position:[0,13,13],fov:42}} dpr={[1,1.5]} fallback={list} gl={{antialias:true,alpha:true}}><Scene station={station} selected={props.selected} onSelect={choose} resolved={props.resolved} busy={props.busy} lens={props.lens} mode={mode} command={cmd} orbit={orbit} locked={props.locked} lineFilter={line} reduced={reduced}/></Canvas></Suspense></MapBoundary>
 <div className="map-line-key">{railLines.filter((l,i)=>i!==2).map(l=><button key={l.code} style={{color:l.color}} onClick={()=>{setLine(line===l.code?'All':l.code);choose(l.names[Math.floor(l.names.length/2)])}}><i style={{background:l.color}}/>{l.code}</button>)}</div>
 <div className="map-controls"><button aria-label="Zoom into map" onClick={()=>send('zoom',.72)}><Plus size={17}/></button><button aria-label="Zoom out of map" onClick={()=>send('zoom',1.35)}><Minus size={17}/></button><button aria-label="Rotate map left" onClick={()=>send('rotate',-.4)}><ArrowLeft size={17}/></button><button aria-label="Rotate map right" onClick={()=>send('rotate',.4)}><ArrowRight size={17}/></button><button aria-label="North up" onClick={()=>send('north')}><Navigation size={17}/></button><button aria-label="Reset map camera" onClick={()=>{setMode('3d');setLine('All');send('reset')}}><RotateCcw size={17}/></button><button aria-label="Focus selected workzone" onClick={()=>send('focus')}><Focus size={17}/></button><span/>{['3d','schematic','track'].map(m=><button key={m} className={mode===m?'active':''} onClick={()=>{setMode(m);send(m==='track'?'track':m==='schematic'?'north':'reset')}}>{m==='3d'?'3D':m==='track'?'Track detail':'Schematic'}</button>)}<button className={orbit?'active':''} aria-label="Toggle presentation orbit" onClick={()=>setOrbit(v=>!v)}><RotateCcw size={15}/>Orbit</button></div>
 <div className="map-caption"><span>Drag to rotate · scroll to zoom · right-drag to pan</span><span>Natural Earth coastline · approximate rail corridors</span></div><details className="map-accessible"><summary>Workzone list / accessible navigation</summary>{zones.map(z=><button key={z.id} onClick={()=>choose(z.station)}>{z.name} · {props.resolved?'Coordinated':z.state}</button>)}</details></section>
}
