"""Regenerate checked-in OpenAPI and TypeScript schema types without a database."""
import json
import re
from pathlib import Path
import sys
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from app.main import app
schema=app.openapi()
(ROOT/"docs/openapi.json").write_text(json.dumps(schema,indent=2)+"\n")

def name(value):return re.sub(r"\W","_",value)

def ts(node):
    if "$ref" in node:return name(node["$ref"].split("/")[-1])
    if "const" in node:return json.dumps(node["const"])
    if "enum" in node:return " | ".join(json.dumps(x) for x in node["enum"])
    for key in ("anyOf","oneOf","allOf"):
        if key in node:return (" & " if key=="allOf" else " | ").join(ts(x) for x in node[key])
    kind=node.get("type")
    if kind=="array":return "("+ts(node.get("items",{}))+")[]"
    if kind=="object" or "properties" in node:
        required=node.get("required",[])
        props=["  "+json.dumps(k)+(":" if k in required else "?:")+" "+ts(v)+";" for k,v in node.get("properties",{}).items()]
        additional=node.get("additionalProperties")
        if additional:props.append("  [key:string]: "+(ts(additional) if isinstance(additional,dict) else "unknown")+";")
        return "{\n"+"\n".join(props)+"\n}"
    return {"string":"string","integer":"number","number":"number","boolean":"boolean","null":"null"}.get(kind,"unknown")

types=["// Generated by scripts/export_contracts.py from FastAPI OpenAPI.\n"]
for key,value in sorted(schema["components"]["schemas"].items()):
    types.append("export type "+name(key)+" = "+ts(value)+";\n")
(ROOT/"frontend/contracts.generated.ts").write_text("\n".join(types))
print(f"Exported {len(schema['paths'])} paths and {len(schema['components']['schemas'])} schemas")
