steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --pull
      - --file
      - railplan-backend/Dockerfile
      - --tag
      - ${_IMAGE}
      - railplan-backend

images:
  - ${_IMAGE}
